# pull official base image
FROM node:alpine as build

# set working directory
WORKDIR /app

ENV PYTHONUNBUFFERED=1
RUN mkdir -p vendor

COPY /musyc/frontend/package*.json ./
COPY /musyc/frontend/vendor/plotly-mini.min.js ./vendor/
# COPY package*.json ./
# COPY /vendor/plotly-mini.min.js ./vendor/

RUN apk update && apk upgrade && apk add --update alpine-sdk && \
    apk add --no-cache bash git openssh make cmake g++
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN npm install 
COPY /musyc/frontend ./
# COPY . ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN apk update \
  && apk add curl \
  && sed -i '/location \/ {$/a try_files \$uri \/index.html;' /etc/nginx/conf.d/default.conf

EXPOSE 80 
ENTRYPOINT ["nginx", "-g", "daemon off;"]
