FROM python:3.9-slim-buster
ARG POSTGRES_PASSWORD
ARG POSTGRES_HOST
ARG POSTGRES_USER
ARG POSTGRES_DBNAME
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DBNAME=$POSTGRES_DBNAME

WORKDIR /app

COPY backend/requirements.txt requirements.txt

RUN python -m pip install --upgrade pip

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY backend/ ./
EXPOSE 80
CMD [ "python", "main.py"]
